name: mentors_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^5.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_native_splash: ^2.2.18

# flutter_native_splash:
#   color: "#B794F4"
#   android: true
#   ios: true
#   web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
