name: mentors_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^5.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  intl: ^0.20.1
  http: ^1.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  flutter_widget_from_html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_native_splash: ^2.2.18

# flutter_native_splash:
#   color: "#B794F4"
#   android: true
#   ios: true
#   web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
