// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-DtnuplifEnl8TdW6n3hrxFE187AvAU',
    appId: '1:1003380789238:web:9ce577e692aeacd6e7c1d7',
    messagingSenderId: '1003380789238',
    projectId: 'mentors-app-fb958',
    authDomain: 'mentors-app-fb958.firebaseapp.com',
    storageBucket: 'mentors-app-fb958.firebasestorage.app',
    measurementId: 'G-69JH5JDSZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5q10PCQinB02mMh0-BQ6gLqrcgmmOHg',
    appId: '1:1003380789238:android:0d5cd186c0d909c5e7c1d7',
    messagingSenderId: '1003380789238',
    projectId: 'mentors-app-fb958',
    storageBucket: 'mentors-app-fb958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIOeK8-5TyJvw-QC23aZ6qHY37yMSfOc',
    appId: '1:1003380789238:ios:3dacedbdba328515e7c1d7',
    messagingSenderId: '1003380789238',
    projectId: 'mentors-app-fb958',
    storageBucket: 'mentors-app-fb958.firebasestorage.app',
    iosBundleId: 'com.example.mentorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIOeK8-5TyJvw-QC23aZ6qHY37yMSfOc',
    appId: '1:1003380789238:ios:3dacedbdba328515e7c1d7',
    messagingSenderId: '1003380789238',
    projectId: 'mentors-app-fb958',
    storageBucket: 'mentors-app-fb958.firebasestorage.app',
    iosBundleId: 'com.example.mentorsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk-DtnuplifEnl8TdW6n3hrxFE187AvAU',
    appId: '1:1003380789238:web:fce7f3db363dec06e7c1d7',
    messagingSenderId: '1003380789238',
    projectId: 'mentors-app-fb958',
    authDomain: 'mentors-app-fb958.firebaseapp.com',
    storageBucket: 'mentors-app-fb958.firebasestorage.app',
    measurementId: 'G-3G8ZVQS6FW',
  );
}
